const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://uatlifekaplan.tmibasl.in/');
  await page.getByRole('textbox', { name: 'Enter User Name' }).click();
  await page.getByRole('textbox', { name: 'Enter User Name' }).fill('ASHU001278409');
  await page.getByRole('textbox', { name: 'Enter Password' }).click();
  await page.getByRole('textbox', { name: 'Enter Password' }).fill('Admin@1234');
  await page.getByRole('button', { name: 'Login    ' }).click();
  await page.getByRole('button', { name: 'menu' }).click();
  await page.locator('a').filter({ hasText: 'Policy Centre' }).click();
  await page.locator('a').filter({ hasText: /^Policy$/ }).click();
  await page.locator('a').filter({ hasText: 'Policy Issuance' }).click();
  await page.getByText('NewRenew').click();
  await page.getByRole('button', { name: 'Non TMIBASL Policy' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select OEM--' }).click();
  await page.getByRole('option', { name: 'FORD' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Previous Vehicle Cover--' }).click();
  await page.getByRole('option', { name: '1 OD + 1 TP' }).click();
  await page.locator('input[name="POLICY_EXPIRY_DATE"]').click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('region', { name: 'Policy Details' }).getByLabel('Choose date', { exact: true }).click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('textbox', { name: 'Previous Policy No *' }).click();
  await page.getByRole('textbox', { name: 'Previous Policy No *' }).fill('23au');
  await page.getByRole('textbox', { name: 'Previous Policy No *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Previous Policy No *' }).fill('23auI6');
  await page.getByRole('combobox', { name: 'OEM * 0' }).click();
  await page.getByRole('option', { name: '45' }).click();
  await page.getByText('--Select Previous OD Policy').click();
  await page.getByRole('option', { name: 'Generali Central Insurance' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Vehicle Cover--' }).click();
  await page.getByRole('option', { name: '1 OD + 1 TP' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Salutation--' }).click();
  await page.getByRole('option', { name: 'MR.' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Pratheesh');
  await page.getByRole('textbox', { name: 'First Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('p');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('m');
  await page.getByRole('textbox', { name: 'Email Id *' }).click();
  await page.getByRole('textbox', { name: 'Email Id *' }).fill('pissaypratheesh999@gmail.com');
  await page.getByRole('textbox', { name: 'Email Id *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Mobile No *' }).fill('9538068222');
  await page.getByRole('textbox', { name: 'VIN (Chassis No) *' }).click();
  await page.getByRole('textbox', { name: 'VIN (Chassis No) *' }).fill('k9d84bn8jskdhfajh');
  await page.getByRole('textbox', { name: 'VIN (Chassis No) *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Engine No *' }).fill('lkjsf923kjf92jkdsfi922299');
  await page.getByText('--Select Make--').click();
  await page.getByRole('option', { name: 'Ford' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Model--' }).click();
  await page.getByRole('option', { name: 'ENDEAVOUR', exact: true }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Variant--' }).click();
  await page.getByRole('option', { name: 'ENDEAVOUR - 4 X 2 AT' }).click();
  await page.getByRole('combobox', { name: 'OEM * ENDEAVOUR', exact: true }).click();
  await page.getByRole('option', { name: 'ESCORT' }).click();
  await page.getByRole('combobox', { name: 'OEM *', exact: true }).click();
  await page.getByRole('option', { name: '--Select Variant--' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Variant--' }).click();
  await page.locator('#menu-VariantId div').first().click();
  await page.locator('#menu-VariantId div').first().click();
  await page.getByRole('option', { name: 'BooM 1stsdfsdf' }).click();
  await page.getByText('Variant--Select Variant--').click();
  await page.locator('#menu-VariantId div').first().click();
  await page.getByRole('button', { name: 'Fetch' }).click();
  await page.getByRole('combobox', { name: 'OEM * BooM 1stsdfsdf' }).click();
  await page.getByRole('option', { name: 'ENDEAVOUR', exact: true }).click();
  await page.getByText('--Select Variant--').click();
  await page.getByRole('option', { name: 'ENDEAVOUR - 4 X 2 AT' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Year of' }).click();
  await page.getByRole('option', { name: '2024' }).click();
  await page.getByRole('combobox', { name: 'OEM * --Select Registration' }).click();
  await page.getByRole('option', { name: 'AHMEDABAD (GJ)' }).click();
  await page.getByText('Customer Residence State--Select Customer Residence State--').click();
  await page.getByRole('option', { name: 'ARUNACHAL PRADESH' }).click();
  await page.locator('input[name="InvoiceDate"]').click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('textbox', { name: 'Choose date', exact: true }).click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('combobox', { name: 'OEM * AHMEDABAD (GJ)' }).click();
  await page.getByRole('option', { name: 'DELHI CENTRAL DL 06 (DL)' }).click();
  await page.getByRole('combobox', { name: 'OEM * ARUNACHAL PRADESH' }).click();
  await page.getByRole('option', { name: 'DELHI' }).click();
  await page.getByRole('textbox', { name: 'GSTIN' }).click();
  await page.getByRole('textbox', { name: 'DL-' }).click();
  await page.getByRole('textbox', { name: 'DL-' }).fill('DL-09');
  await page.getByRole('textbox', { name: 'DL-' }).press('Tab');
  await page.getByRole('textbox', { name: 'RAA' }).fill('RAA');
  await page.getByRole('textbox', { name: '5445' }).click();
  await page.getByRole('textbox', { name: '5445' }).fill('5445');
  await page.getByLabel('Additional Discounts').getByRole('button', { name: 'Yes' }).first().click();
  await page.getByRole('combobox', { name: 'OEM * --Select Entitled NCB' }).click();
  await page.getByRole('option', { name: '20' }).click();
  await page.getByLabel('Additional Discounts').getByRole('button', { name: 'Yes' }).nth(1).click();
  await page.getByText('--Select Voluntary Excess').click();
  await page.getByRole('option', { name: '2500' }).click();
  await page.getByLabel('Additional Discounts').getByRole('button', { name: 'Yes' }).nth(2).click();
  await page.getByLabel('Additional Discounts').getByRole('button', { name: 'Yes' }).nth(3).click();
  await page.getByLabel('Additional Discounts').getByRole('button', { name: 'Yes' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Electrical Accessories Price', exact: true }).click();
  await page.getByRole('textbox', { name: 'Electrical Accessories Price', exact: true }).fill('34334');
  await page.getByRole('textbox', { name: 'Non Electrical Accessories' }).click();
  await page.getByRole('textbox', { name: 'Non Electrical Accessories' }).fill('3423');
  await page.getByRole('textbox', { name: 'BiFuel Kit Price' }).click();
  await page.getByRole('textbox', { name: 'BiFuel Kit Price' }).fill('3243');
  await page.locator('#divGeoExtnsn').click();
  await page.getByRole('option', { name: 'Nepal' }).click();
  await page.getByRole('option', { name: 'Bhutan' }).click();
  await page.locator('#menu-GeoArea div').first().click();
  await page.locator('#divpacoverpaiddriver').getByRole('button', { name: 'Yes' }).click();
  await page.locator('div').filter({ hasText: /^PA Cover Amount \(₹\)--Select PA Cover Amount \(₹\)--$/ }).first().click();
  await page.getByRole('option', { name: '30000' }).click();
  await page.getByRole('combobox', { name: 'Legal Liability - Employees' }).click();
  await page.getByRole('option', { name: '2' }).click();
  await page.getByRole('button', { name: 'Get Quotes' }).click();
  await page.getByRole('textbox', { name: '5445' }).click();
  await page.getByRole('textbox', { name: '5445' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: '5445' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: '5445' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: '5445' }).fill('9445');
  await page.getByRole('button', { name: 'Get Quotes' }).click();
  await page.getByRole('button', { name: '₹ 22513 BUY NOW' }).click();
  await page.locator('input[name="DOB"]').click();
  await page.getByRole('button', { name: 'calendar view is open, switch' }).click();
  await page.getByRole('radio', { name: '1992' }).click();
  await page.getByRole('radio', { name: 'January' }).click();
  await page.getByRole('gridcell', { name: '16' }).click();
  await page.getByRole('textbox', { name: 'Address Line 1 *' }).click();
  await page.getByRole('textbox', { name: 'Address Line 1 *' }).fill('lksdjf,23de,3e');
  await page.locator('div').filter({ hasText: /^Address Line 2$/ }).nth(1).click();
  await page.getByText('--Select City--').click();
  await page.getByRole('option', { name: 'DELHI', exact: true }).click();
  await page.locator('#mui-component-select-PIN').click();
  await page.getByRole('option', { name: '110006' }).click();
  await page.getByRole('textbox', { name: 'PAN No.' }).click();
  await page.getByRole('textbox', { name: 'PAN No.' }).fill('BUBpp6633h');
  await page.locator('.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-md-4.requiredField > .MuiFormControl-root').first().click();
  await page.getByRole('option', { name: 'Automobile Association of Eastern India' }).click();
  await page.getByRole('textbox', { name: 'Membership No. *' }).click();
  await page.getByRole('textbox', { name: 'Membership No. *' }).fill('324242');
  await page.locator('#mui-component-select-AAMonth').click();
  await page.getByRole('option', { name: 'Apr' }).click();
  await page.getByRole('textbox', { name: 'Year *' }).click();
  await page.getByRole('textbox', { name: 'Year *' }).click();
  await page.getByRole('textbox', { name: 'Year *' }).fill('2028');
  await page.getByRole('textbox', { name: 'Make *' }).click();
  await page.getByRole('textbox', { name: 'Make *' }).fill('FORD');
  await page.getByRole('textbox', { name: 'Model *' }).click();
  await page.getByRole('textbox', { name: 'Model *' }).fill('HARRIER');
  await page.getByRole('textbox', { name: 'Variant *' }).click();
  await page.getByRole('textbox', { name: 'Variant *' }).fill('OD');
  await page.locator('#mui-component-select-PREV_VEH_MANU_YEAR').click();
  await page.getByRole('option', { name: '2023' }).click();
  await page.getByRole('textbox', { name: 'Chassis No. *' }).click();
  await page.getByRole('textbox', { name: 'Chassis No. *' }).fill('3kl483dwehihjfoiw');
  await page.getByRole('textbox', { name: 'Chassis No. *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Engine No. *' }).fill('ldfjks2o4fklwjfiowwiejewf');
  await page.getByRole('textbox', { name: 'Chassis No. *' }).click();
  await page.getByRole('textbox', { name: 'Registration No. *' }).click();
  await page.getByRole('textbox', { name: 'Registration No. *' }).fill('DL09H9823');
  await page.getByRole('textbox', { name: 'Previous Policy No. *' }).click();
  await page.getByRole('textbox', { name: 'Previous Policy No. *' }).fill('slkdjfoi239e');
  await page.getByRole('checkbox', { name: 'controlled' }).check();
  await page.locator('input[name="PREV_VEH_NCB_EFFECTIVE_DATE_NONVISOF"]').click();
  await page.getByText('12345678910111213141516171819202122232425262728293031').click();
  await page.getByRole('textbox', { name: 'Choose date, selected date is Oct 15,' }).click();
  await page.getByRole('gridcell', { name: '24' }).click();
  await page.getByRole('textbox', { name: 'Choose date, selected date is Oct 24,' }).click();
  await page.getByRole('gridcell', { name: '10' }).click();
  await page.getByRole('textbox', { name: 'Choose date, selected date is Oct 10,' }).click();
  await page.locator('div').filter({ hasText: 'Select dateFri, Oct 10October' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Choose date, selected date is Oct 17,' }).click();
  await page.getByRole('gridcell', { name: '7', exact: true }).click();
  await page.locator('input[name="PREV_VEH_POLICYSTARTDATE"]').click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('textbox', { name: 'Choose date', exact: true }).click();
  await page.getByRole('gridcell', { name: '16' }).click();
  await page.getByRole('combobox', { name: 'Salutation * --Select Insurance Company--' }).click();
  await page.getByRole('option', { name: 'Export Credit Guarantee' }).click();
  await page.getByRole('textbox', { name: 'Office Address *' }).click();
  await page.getByRole('textbox', { name: 'Office Address *' }).fill('the office');
  await page.getByRole('textbox', { name: 'Nominee Name *' }).click();
  await page.getByRole('textbox', { name: 'Nominee Name *' }).fill('boh');
  await page.getByRole('textbox', { name: 'Nominee Age *' }).click();
  await page.getByRole('textbox', { name: 'Nominee Age *' }).fill('34');
  await page.locator('#mui-component-select-NomineeRelation').click();
  await page.getByRole('option', { name: 'DAUGHTER' }).click();
  await page.locator('#mui-component-select-NomineeGender').click();
  await page.getByRole('option', { name: 'Female' }).click();
  await page.locator('#mui-component-select-PAYMENT_MODE').click();
  await page.getByRole('option', { name: 'Customer\'s Cheque' }).click();
  await page.getByRole('combobox', { name: 'Salutation * --Select DP Name' }).click();
  await page.getByRole('option', { name: 'Ashutosh DP' }).click();
  await page.getByRole('button', { name: 'Proposal Preview' }).click();
  await page.getByRole('textbox', { name: 'Choose date, selected date is Oct 16,' }).click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('button', { name: 'Proposal Preview' }).click();
  await page.locator('input[name="PREV_VEH_POLICYENDDATE"]').click();
  await page.getByRole('button', { name: 'calendar view is open, switch' }).click();
  await page.getByRole('radio', { name: '2026' }).click();
  await page.getByRole('radio', { name: 'October' }).click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('button', { name: 'Proposal Preview' }).click();
  await page.getByRole('textbox', { name: 'Choose date, selected date is Oct 17, 2026' }).click();
  await page.getByRole('gridcell', { name: '16' }).click();
  await page.getByRole('button', { name: 'Proposal Preview' }).click();
  await page.locator('label').filter({ hasText: 'I hereby agree to receive a' }).getByTestId('CheckBoxOutlineBlankIcon').click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').click();
  await page.getByTestId('UploadIcon').first().click();
  await page.getByText('Browse files').first().click();
  await page.locator('body').setInputFiles('GitHub_Interview_Questions_Cheat_Sheet.pdf');
  await page.getByText('Limit 15MB per file.').nth(1).click();
  await page.getByText('Browse files').nth(1).click();
  await page.locator('body').setInputFiles('GitHub_Interview_Questions_Cheat_Sheet.pdf');
  await page.getByText('Browse files').click();
  await page.locator('body').setInputFiles('GitHub_Interview_Questions_Cheat_Sheet.pdf');
  await page.getByRole('button', { name: 'Verify KYC' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.close();

  // ---------------------
  await context.close();
  await browser.close();
})();